Split Acc Export when building super mechanisms
thorstenhater/nmlcc pull request #28
Opened 2022-11-10 19:37 UTC by thorstenhater

- only density mechanisms are squashed now, that excludes concentration models, which scare me
- that might change (exclusion, not the terror of the eldritch) in the future
- add blessed rho_factor unit, which is likely bogus (TODO, but this is used in our tests and a single paper only. Still...)
- fix a bug when exporting conc-models (see?!) which turned `paint` into `default`
- parse bundle input one less time
- appease clippy and fmt even more by using snake case

2022-11-13 23:29 UTC, llandsmeer commented on src/acc.rs
> -impl SexpConfig {
Yes the entire SexpConfig thing just for adding the prefix was a bit ugly..

2022-11-14 10:43 UTC, llandsmeer requested changes

2022-11-14 13:22 UTC, thorstenhater commented on src/acc.rs
> +fn get_inhomogeneous_parameters(
Yes, definitely! This should have a better name by by now.

2022-11-18 15:59 UTC, llandsmeer approved these changes

2022-11-18 19:09 UTC, merged