Markdownify
thorstenhater/nmlcc pull request #5
Opened 2022-02-04 16:43 UTC by brenthuisman

:)

2022-02-07 08:48 UTC, thorstenhater requested changes

2022-02-07 08:48 UTC, thorstenhater commented on doc/nml.md
> +# Introduction
While I am fine with changing over README (the Org renderer on GH is not a nice as I would like), this file is more my personal notes than anything else. Orgmode holds a number of advantages there (for me at least), so I would prefer keeping that. If it ever turns into more that that, fine ;)

2022-02-07 18:14 UTC, thorstenhater reviewed
Tiny comment on the TLDR.

2022-02-08 12:16 UTC, brenthuisman commented on doc/nml.org
> +*TL;DR*: NeuroML is a dialect of the LEMS format. All NeuroML is LEMS.
Is NeuroML2 a library though? Isn't that jNML, implementing the NML2 spec?

2022-02-08 12:17 UTC, thorstenhater commented on doc/nml.org
> +*TL;DR*: NeuroML is a dialect of the LEMS format. All NeuroML is LEMS.
jnml is an executable to interpret LEMS/NML2

2022-02-08 12:47 UTC, brenthuisman commented on doc/nml.org
> +*TL;DR*: NeuroML is a dialect of the LEMS format. All NeuroML is LEMS.
The schemata, as in the XSD files, is then 'the library'?

2022-02-08 17:49 UTC, thorstenhater commented on doc/nml.org
> +*TL;DR*: NeuroML is a dialect of the LEMS format. All NeuroML is LEMS.
No, the 'library' is whatever is in CoreTypes. XSD is syntax only in this analogy.

2022-02-09 09:56 UTC, brenthuisman commented on doc/nml.org
> +*TL;DR*: NeuroML is a dialect of the LEMS format. All NeuroML is LEMS.
Right, but where do I find the library in https://github.com/NeuroML/NeuroML2/ ? Only schema's as far as I can see.

So, it seems to me the word 'library' can be left out: LEMS is an XML dialect/language, and NeuroML2 defines itself in that language.

2022-02-09 12:09 UTC, thorstenhater approved these changes
👍

2022-02-09 12:10 UTC, merged